/**
 * Generated by @skyleague/therefore@v1.0.0-local
 * Do not manually touch this
 */
/* eslint-disable */
import AjvValidator from 'ajv'
import type { ValidateFunction } from 'ajv'

export interface FirehoseRecordMetadata {
    shardId: string
    partitionKey: string
    approximateArrivalTimestamp: number
    sequenceNumber: string
    subsequenceNumber: string
}

export interface FirehoseTransformationEventRecord {
    recordId: string
    approximateArrivalTimestamp: number
    data: string
    kinesisRecordMetadata?: FirehoseRecordMetadata | undefined
}

export const FirehoseTransformationEventRecord = {
    validate:
        require('./schemas/firehose-transformation-event-record.schema.js') as ValidateFunction<FirehoseTransformationEventRecord>,
    get schema() {
        return FirehoseTransformationEventRecord.validate.schema
    },
    get errors() {
        return FirehoseTransformationEventRecord.validate.errors ?? undefined
    },
    is: (o: unknown): o is FirehoseTransformationEventRecord => FirehoseTransformationEventRecord.validate(o) === true,
    assert: (o: unknown) => {
        if (!FirehoseTransformationEventRecord.validate(o)) {
            throw new AjvValidator.ValidationError(FirehoseTransformationEventRecord.errors ?? [])
        }
    },
} as const

export interface FirehoseTransformationEvent {
    invocationId: string
    deliveryStreamArn: string
    sourceKinesisStreamArn?: string | undefined
    region: string
    records: FirehoseTransformationEventRecord[]
}

export const FirehoseTransformationEvent = {
    validate: require('./schemas/firehose-transformation-event.schema.js') as ValidateFunction<FirehoseTransformationEvent>,
    get schema() {
        return FirehoseTransformationEvent.validate.schema
    },
    get errors() {
        return FirehoseTransformationEvent.validate.errors ?? undefined
    },
    is: (o: unknown): o is FirehoseTransformationEvent => FirehoseTransformationEvent.validate(o) === true,
    assert: (o: unknown) => {
        if (!FirehoseTransformationEvent.validate(o)) {
            throw new AjvValidator.ValidationError(FirehoseTransformationEvent.errors ?? [])
        }
    },
} as const
